import type { EnvironmentDef } from './types';

/**
 * Scenery themes used by highlight cinematics. Each track references one by
 * `env`. New looks (e.g. snow, jungle) can be added here and in src/art/scenery.
 */
export const ENVIRONMENTS: EnvironmentDef[] = [
  {
    id: 'riviera',
    name: 'Harbour',
    sky: ['#5DB8F2', '#D4EEFF'],
    skyNight: ['#0B1026', '#2A3563'],
    far: 'sea',
    farColor: '#2F78B7',
    ground: '#9A9DA3',
    props: ['yachts', 'buildings', 'palms', 'billboards'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'armco',
  },
  {
    id: 'coastal',
    name: 'Coast',
    sky: ['#6CC6FF', '#E6F6FF'],
    skyNight: ['#0A1330', '#26375F'],
    far: 'sea',
    farColor: '#3688C9',
    ground: '#D6C08E',
    props: ['palms', 'grandstand', 'billboards'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'tyres',
  },
  {
    id: 'forest',
    name: 'Forest',
    sky: ['#8FC7EE', '#E2F1FA'],
    skyNight: ['#081223', '#1D2D45'],
    far: 'forest',
    farColor: '#2E5A3A',
    ground: '#4F8B3F',
    props: ['pines', 'grandstand', 'billboards'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'armco',
  },
  {
    id: 'desert',
    name: 'Desert',
    sky: ['#FFAE66', '#FFE2B5'],
    skyNight: ['#150E2B', '#3E2A55'],
    far: 'dunes',
    farColor: '#D39A5E',
    ground: '#E2BE88',
    props: ['grandstand', 'billboards', 'lights'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'tyres',
  },
  {
    id: 'city',
    name: 'City',
    sky: ['#86B2DC', '#DAE8F5'],
    skyNight: ['#060918', '#1B2043'],
    far: 'city',
    farColor: '#46587A',
    ground: '#6B7078',
    props: ['buildings', 'billboards', 'lights'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'wall',
  },
  {
    id: 'mountain',
    name: 'Mountains',
    sky: ['#94C4EE', '#EAF4FB'],
    skyNight: ['#08101F', '#1F2C44'],
    far: 'mountains',
    farColor: '#6A7D98',
    ground: '#5C8E45',
    props: ['pines', 'grandstand'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'armco',
  },
  {
    id: 'parkland',
    name: 'Parkland',
    sky: ['#96CFFF', '#EAF6FF'],
    skyNight: ['#0A1226', '#22304F'],
    far: 'hills',
    farColor: '#6C9A58',
    ground: '#5BA249',
    props: ['trees', 'grandstand', 'billboards'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'tyres',
  },
  {
    id: 'plains',
    name: 'Plains',
    sky: ['#A3D0F0', '#F2F8FC'],
    skyNight: ['#0B1326', '#243150'],
    far: 'plains',
    farColor: '#9AB268',
    ground: '#8BB25A',
    props: ['grandstand', 'billboards', 'trees'],
    kerb: ['#E4002B', '#FFFFFF'],
    barrier: 'tyres',
  },
  {
    id: 'oval',
    name: 'Speedway',
    sky: ['#86C4F0', '#E5F2FC'],
    skyNight: ['#070C1E', '#1D2848'],
    far: 'plains',
    farColor: '#8FA86A',
    ground: '#5A9C45',
    props: ['grandstand', 'lights', 'billboards'],
    kerb: ['#FFFFFF', '#1A1A1A'],
    barrier: 'wall',
  },
];

export const ENV_MAP: Record<string, EnvironmentDef> = Object.fromEntries(ENVIRONMENTS.map((e) => [e.id, e]));

export function environment(id: string): EnvironmentDef {
  return ENV_MAP[id] ?? ENVIRONMENTS[6];
}

/** Fictional sponsors for billboards, liveries and events. */
export const SPONSORS = [
  'VOLTRIX',
  'NIMBARA AIR',
  'QUANTIVA BANK',
  'AERIVO MOBILE',
  'KAIROKU',
  'FIZZORA COLA',
  'ORBYTE',
  'VIREOLA',
  'SOLACIA',
  'ZENTRIQ',
  'HELIOSPARK',
  'LUMENARA',
  'CRESTVALE',
  'GRIDLY',
  'FROSTLINE',
  'MISTRAVIA AIR',
  'KOIKO NOODLE',
  'RHINEX TOOLS',
  'PULSEWAVE AUDIO',
  'GLACIO',
];
