import { EUROPE } from './names/europe';
import { WORLD_NAMES } from './names/world';
import type { NameGroup } from './types';

/** Name pools per cultural group (referenced by nations via `nameGroup`). */
export const NAME_GROUPS: Record<string, NameGroup> = { ...EUROPE, ...WORLD_NAMES };

/**
 * Famous real racing drivers. The pools already leave out distinctive surnames, but
 * common ones (Clark, Jones, Evans…) could still pair up into a real person's name,
 * so the generator re-rolls any full name on this list. Compared case- and
 * accent-insensitively.
 */
const FAMOUS_DRIVERS = [
  // Formula 1 champions and stars
  'Alan Jones',
  'Jim Clark',
  'Jackie Stewart',
  'Graham Hill',
  'Damon Hill',
  'Phil Hill',
  'Mika Salo',
  'Mika Hakkinen',
  'Gerhard Berger',
  'Nigel Mansell',
  'Ayrton Senna',
  'Alain Prost',
  'Niki Lauda',
  'James Hunt',
  'Jody Scheckter',
  'Nelson Piquet',
  'Keke Rosberg',
  'Nico Rosberg',
  'Michael Schumacher',
  'Ralf Schumacher',
  'Mick Schumacher',
  'Sebastian Vettel',
  'Lewis Hamilton',
  'Fernando Alonso',
  'Kimi Raikkonen',
  'Jenson Button',
  'Max Verstappen',
  'Jos Verstappen',
  'Charles Leclerc',
  'Lando Norris',
  'Oscar Piastri',
  'George Russell',
  'Carlos Sainz',
  'Sergio Perez',
  'Mark Webber',
  'David Coulthard',
  'Eddie Irvine',
  'Rubens Barrichello',
  'Felipe Massa',
  'Juan Pablo Montoya',
  'Jacques Villeneuve',
  'Gilles Villeneuve',
  'Jack Brabham',
  'Denny Hulme',
  'Jochen Rindt',
  'John Surtees',
  'Emerson Fittipaldi',
  'Mario Andretti',
  'Juan Manuel Fangio',
  'Alberto Ascari',
  'Stirling Moss',
  'Mike Hawthorn',
  'Giuseppe Farina',
  'Valtteri Bottas',
  'Daniel Ricciardo',
  'Pierre Gasly',
  'Esteban Ocon',
  'Yuki Tsunoda',
  'Alexander Albon',
  'Lance Stroll',
  'Nico Hulkenberg',
  'Kevin Magnussen',
  'Guanyu Zhou',
  'Zhou Guanyu',
  'Logan Sargeant',
  'Liam Lawson',
  'Oliver Bearman',
  'Kimi Antonelli',
  'Andrea Kimi Antonelli',
  'Franco Colapinto',
  'Isack Hadjar',
  'Gabriel Bortoleto',
  'Jack Doohan',
  'Robert Kubica',
  'Heikki Kovalainen',
  'Romain Grosjean',
  'Pastor Maldonado',
  'Marcus Ericsson',
  'Felipe Nasr',
  'Daniil Kvyat',
  'Nicholas Latifi',
  'Antonio Giovinazzi',
  'Heinz-Harald Frentzen',
  'Jarno Trulli',
  'Giancarlo Fisichella',
  'Jean Alesi',
  'Riccardo Patrese',
  'Rene Arnoux',
  'Didier Pironi',
  'Jacques Laffite',
  'Ronnie Peterson',
  'Dan Gurney',
  'Bruce McLaren',
  'Jochen Mass',
  'Martin Brundle',
  'Johnny Herbert',
  'Mark Blundell',
  'Alexander Wurz',
  'Nick Heidfeld',
  'Timo Glock',
  'Vitaly Petrov',
  'Kamui Kobayashi',
  'Takuma Sato',
  'Kazuki Nakajima',
  'Stoffel Vandoorne',
  'Pascal Wehrlein',
  'Sebastien Buemi',
  'Sebastien Bourdais',
  'Paul di Resta',
  'Adrian Sutil',
  // IndyCar / endurance / rallying
  'Scott Dixon',
  'Will Power',
  'Alex Palou',
  'Josef Newgarden',
  'Colton Herta',
  "Pato O'Ward",
  'Helio Castroneves',
  'Dario Franchitti',
  'Tony Kanaan',
  'Michael Andretti',
  'Marco Andretti',
  'Al Unser',
  'Bobby Unser',
  'A. J. Foyt',
  'Rick Mears',
  'Danica Patrick',
  'Tom Kristensen',
  'Jacky Ickx',
  'Derek Bell',
  'Allan McNish',
  'Andre Lotterer',
  'Benoit Treluyer',
  'Marcel Fassler',
  'Brendon Hartley',
  'Mike Conway',
  'Jose Maria Lopez',
  'Kazuki Nakajima',
  'Sebastien Loeb',
  'Sebastien Ogier',
  'Colin McRae',
  'Carlos Sainz Sr',
  'Juha Kankkunen',
  'Tommi Makinen',
  'Kalle Rovanpera',
  'Ott Tanak',
  'Thierry Neuville',
  'Elfyn Evans',
  'Mitch Evans',
  'Petter Solberg',
  'Marcus Gronholm',
  'Davy Jones',
  'Jimmie Johnson',
  'Jeff Gordon',
  'Dale Earnhardt',
  'Richard Petty',
  'Kyle Busch',
  'Kurt Busch',
  'Tony Stewart',
  'Kyle Larson',
  'Chase Elliott',
];

const fold = (s: string) =>
  s
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z' ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();

const BLOCKED = new Set(FAMOUS_DRIVERS.map(fold));

/** True when a generated name would belong to a famous real racing driver. */
export function isFamousDriverName(first: string, last: string): boolean {
  return BLOCKED.has(fold(`${first} ${last}`));
}
