import type { SeriesDef, SpecialEventDef } from './types';

const F1_POINTS = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1];
const AMERICAN_POINTS = [50, 40, 35, 32, 30, 28, 26, 24, 22, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10];

/**
 * The championships of the Chequered Lives universe. Every name is fictional.
 * Add a new series by appending a definition here and teams in teams.ts.
 */
export const SERIES: SeriesDef[] = [
  {
    id: 'prime',
    name: 'Formula Prime',
    short: 'PRIME',
    discipline: 'formula',
    carClass: 'formula',
    tier: 1,
    prestige: 100,
    carsPerTeam: 2,
    carImportance: 0.62,
    perfSpread: 15,
    points: F1_POINTS,
    fastestLapBonus: 1,
    minAge: 17,
    ovrBand: [80, 95],
    paceFactor: 1,
    raceMinutes: 95,
    eventStyle: 'grandPrix',
    calendar: [
      { track: 'harbourside' },
      { track: 'chaophraya' },
      { track: 'pearlriver' },
      { track: 'sakurahills' },
      { track: 'skeletoncoast' },
      { track: 'costadelsol' },
      { track: 'riviera', special: 'riviera' },
      { track: 'ileverte' },
      { track: 'alpenblick' },
      { track: 'silverdale' },
      { track: 'hautesfagnes' },
      { track: 'zeewind' },
      { track: 'valleverde' },
      { track: 'canyonridge' },
      { track: 'sierraalta' },
      { track: 'serraazul' },
      { track: 'neonstrip' },
      { track: 'deccan' },
    ],
    rotation: ['nordhang', 'costaatlantica', 'highveld', 'aurora', 'pampas'],
    color: '#D0102B',
    accent: '#FF5A4A',
    description: 'The pinnacle. Twenty of the fastest drivers on Earth, ten teams, one world title.',
    salary: [900, 30000],
    paySeat: 9000,
    path: 'formula',
    promotesTo: [],
  },
  {
    id: 'apex',
    name: 'Formula Apex',
    short: 'APEX',
    discipline: 'formula',
    carClass: 'formula',
    tier: 2,
    prestige: 68,
    carsPerTeam: 2,
    carImportance: 0.34,
    perfSpread: 9,
    points: F1_POINTS,
    fastestLapBonus: 1,
    minAge: 16,
    maxAge: 26,
    ovrBand: [68, 85],
    paceFactor: 1.08,
    raceMinutes: 45,
    eventStyle: 'round',
    calendar: [
      { track: 'skeletoncoast' },
      { track: 'pearlriver' },
      { track: 'costadelsol' },
      { track: 'riviera' },
      { track: 'alpenblick' },
      { track: 'silverdale' },
      { track: 'hautesfagnes' },
      { track: 'zeewind' },
      { track: 'valleverde' },
      { track: 'nordhang' },
      { track: 'costaatlantica' },
      { track: 'serraazul' },
    ],
    rotation: ['sierraalta', 'deccan', 'highveld'],
    color: '#1E88E5',
    accent: '#64B5F6',
    description: 'The final step before Formula Prime. Win here and the big teams come calling.',
    salary: [60, 400],
    paySeat: 1500,
    path: 'formula',
    promotesTo: ['prime'],
  },
  {
    id: 'contender',
    name: 'Formula Contender',
    short: 'CONTENDER',
    discipline: 'formula',
    carClass: 'formulaJunior',
    tier: 3,
    prestige: 48,
    carsPerTeam: 2,
    carImportance: 0.3,
    perfSpread: 8,
    points: F1_POINTS,
    fastestLapBonus: 1,
    minAge: 15,
    maxAge: 23,
    ovrBand: [60, 76],
    paceFactor: 1.15,
    raceMinutes: 35,
    eventStyle: 'round',
    calendar: [
      { track: 'costadelsol' },
      { track: 'alpenblick' },
      { track: 'silverdale' },
      { track: 'hautesfagnes' },
      { track: 'zeewind' },
      { track: 'valleverde' },
      { track: 'nordhang' },
      { track: 'aurora' },
      { track: 'costaatlantica' },
      { track: 'highveld' },
    ],
    rotation: ['pampas', 'skeletoncoast'],
    color: '#8E24AA',
    accent: '#CE93D8',
    description: 'Thirty-minute sprints, wheel-to-wheel chaos, and scouts watching every move.',
    salary: [0, 80],
    paySeat: 600,
    path: 'formula',
    promotesTo: ['apex'],
  },
  {
    id: 'cadet',
    name: 'Formula Cadet',
    short: 'CADET',
    discipline: 'formula',
    carClass: 'formulaJunior',
    tier: 4,
    prestige: 30,
    carsPerTeam: 2,
    carImportance: 0.22,
    perfSpread: 7,
    points: F1_POINTS,
    fastestLapBonus: 1,
    minAge: 15,
    maxAge: 20,
    ovrBand: [50, 68],
    paceFactor: 1.24,
    raceMinutes: 25,
    eventStyle: 'round',
    calendar: [
      { track: 'aurora' },
      { track: 'zeewind' },
      { track: 'nordhang' },
      { track: 'alpenblick' },
      { track: 'silverdale' },
      { track: 'valleverde' },
      { track: 'costaatlantica' },
      { track: 'pampas' },
      { track: 'highveld' },
      { track: 'costadelsol' },
    ],
    rotation: ['hautesfagnes', 'deccan'],
    color: '#FB8C00',
    accent: '#FFB74D',
    description: 'Where it all begins. Teenagers, first wings, and parents biting their nails.',
    salary: [0, 20],
    paySeat: 250,
    path: 'formula',
    promotesTo: ['contender'],
  },
  {
    id: 'endurance',
    name: 'Global Endurance Championship',
    short: 'GEC',
    discipline: 'endurance',
    carClass: 'prototype',
    tier: 1.5,
    prestige: 80,
    carsPerTeam: 2,
    carImportance: 0.55,
    perfSpread: 9,
    points: F1_POINTS,
    minAge: 18,
    ovrBand: [70, 88],
    paceFactor: 1.07,
    raceMinutes: 360,
    eventStyle: 'endurance',
    calendar: [
      { track: 'everglade', hours: 12 },
      { track: 'costaatlantica', hours: 8 },
      { track: 'hautesfagnes', hours: 6 },
      { track: 'grandouest', hours: 24, special: 'france24', name: '24 Hours of France', double: true },
      { track: 'silverdale', hours: 6 },
      { track: 'serraazul', hours: 6 },
      { track: 'sakurahills', hours: 6 },
      { track: 'skeletoncoast', hours: 8 },
    ],
    color: '#00BFA5',
    accent: '#64FFDA',
    description: 'Hypercar prototypes, three-driver crews, racing through the night. Home of the 24 Hours of France.',
    salary: [250, 2500],
    paySeat: 2500,
    path: 'sportscar',
    promotesTo: [],
    crewSize: 3,
  },
  {
    id: 'american',
    name: 'American Open-Wheel Championship',
    short: 'AOWC',
    discipline: 'american',
    carClass: 'indy',
    tier: 1.8,
    prestige: 74,
    carsPerTeam: 2,
    carImportance: 0.3,
    perfSpread: 8,
    points: AMERICAN_POINTS,
    poleBonus: 1,
    minAge: 18,
    ovrBand: [68, 86],
    paceFactor: 1.03,
    raceMinutes: 105,
    eventStyle: 'american',
    calendar: [
      { track: 'seaside' },
      { track: 'twinrivers' },
      { track: 'canyonridge' },
      { track: 'greatlakes' },
      { track: 'heartland', special: 'heartland500', name: 'Heartland 500', laps: 200, double: true },
      { track: 'prairie' },
      { track: 'ileverte' },
      { track: 'magnolia' },
      { track: 'neonstrip' },
      { track: 'sierraalta' },
      { track: 'pacificcrest' },
      { track: 'everglade' },
    ],
    color: '#1565C0',
    accent: '#EF5350',
    description: 'Ovals at 230 mph, street fights and road courses. The Heartland 500 is the one they all want.',
    salary: [200, 4000],
    paySeat: 1800,
    path: 'american',
    promotesTo: [],
  },
  {
    id: 'gt',
    name: 'GT World Series',
    short: 'GTWS',
    discipline: 'gt',
    carClass: 'gt',
    tier: 2.5,
    prestige: 58,
    carsPerTeam: 2,
    carImportance: 0.4,
    perfSpread: 8,
    points: F1_POINTS,
    minAge: 17,
    ovrBand: [62, 82],
    paceFactor: 1.2,
    raceMinutes: 60,
    eventStyle: 'round',
    calendar: [
      { track: 'valleverde' },
      { track: 'silverdale' },
      { track: 'nordhang' },
      { track: 'costaatlantica' },
      { track: 'mountkurrajong', special: 'kurrajong1000', name: 'Kurrajong 1000', double: true },
      { track: 'sakurahills' },
      { track: 'hautesfagnes' },
      { track: 'pacificcrest' },
      { track: 'highveld' },
      { track: 'aurora' },
    ],
    rotation: ['zeewind', 'harbourside', 'deccan'],
    color: '#F9A825',
    accent: '#FFE082',
    description: 'Road-car silhouettes, manufacturer rivalries and door-to-door sprint racing.',
    salary: [80, 900],
    paySeat: 700,
    path: 'sportscar',
    promotesTo: ['endurance'],
  },
];

export const SERIES_MAP: Record<string, SeriesDef> = Object.fromEntries(SERIES.map((s) => [s.id, s]));

export function series(id: string): SeriesDef {
  return SERIES_MAP[id] ?? SERIES[0];
}

/** Crown-jewel events. Winning them is tracked separately for legacy and records. */
export const SPECIAL_EVENTS: SpecialEventDef[] = [
  {
    id: 'riviera',
    name: 'Principality Grand Prix',
    series: 'prime',
    short: 'Riviera GP',
    description: 'Formula Prime around the harbour streets. Qualifying is everything.',
    legacy: 25,
    emoji: '👑',
  },
  {
    id: 'france24',
    name: '24 Hours of France',
    series: 'endurance',
    short: '24h of France',
    description: 'Twice around the clock on the fastest road course in the world.',
    legacy: 35,
    emoji: '🕛',
  },
  {
    id: 'heartland500',
    name: 'Heartland 500',
    series: 'american',
    short: 'Heartland 500',
    description: '200 laps, 33 rows of bravery, the biggest crowd in racing.',
    legacy: 35,
    emoji: '🏁',
  },
  {
    id: 'kurrajong1000',
    name: 'Kurrajong 1000',
    series: 'gt',
    short: 'Kurrajong 1000',
    description: 'A thousand kilometres up and down the mountain. Walls, no mercy.',
    legacy: 12,
    emoji: '⛰️',
  },
];

export const SPECIAL_MAP: Record<string, SpecialEventDef> = Object.fromEntries(SPECIAL_EVENTS.map((s) => [s.id, s]));

/** Winning all three is the Triple Crown. */
export const TRIPLE_CROWN = ['riviera', 'france24', 'heartland500'];

/** Formula ladder in promotion order (bottom to top). */
export const FORMULA_LADDER = ['cadet', 'contender', 'apex', 'prime'];
