import type { FamilyDef, PersonalityDef } from './types';

export const PERSONALITIES: PersonalityDef[] = [
  {
    id: 'golden',
    label: 'Golden Child',
    emoji: '🌟',
    description: 'Destined for greatness — or so everyone keeps saying. Teams queue up, expectations crush.',
    devRate: 1.05,
    repGain: 1.4,
    fanGain: 1.5,
    incidentMult: 1,
    pressure: 0.3,
    offerMult: 1.4,
    ageShift: 0,
    duel: 0,
    teamDrift: 0,
  },
  {
    id: 'iceCold',
    label: 'Ice Cold',
    emoji: '🧊',
    description: 'Nonchalant. Nothing rattles you. Title deciders feel like Tuesday.',
    devRate: 1,
    repGain: 1,
    fanGain: 0.8,
    incidentMult: 0.85,
    pressure: 1,
    offerMult: 1,
    ageShift: 0,
    duel: 0.5,
    teamDrift: 0,
  },
  {
    id: 'bigEgo',
    label: 'Big Ego',
    emoji: '👑',
    description: 'You are the best driver on the grid. Just ask you. Great in duels, awful with teammates.',
    devRate: 1,
    repGain: 1.1,
    fanGain: 1.2,
    incidentMult: 1.15,
    pressure: 0.7,
    offerMult: 0.9,
    ageShift: 0,
    duel: 2,
    teamDrift: -4,
  },
  {
    id: 'loyal',
    label: 'Loyal',
    emoji: '🤝',
    description: 'Team first, always. Teams love you and fight to keep you.',
    devRate: 1,
    repGain: 1,
    fanGain: 1,
    incidentMult: 0.95,
    pressure: 0.5,
    offerMult: 0.8,
    ageShift: 1,
    duel: 0,
    teamDrift: 5,
  },
  {
    id: 'mercenary',
    label: 'Mercenary',
    emoji: '💼',
    description: "The Traitor. You'll sign for whoever's fastest this week. More offers, less trust.",
    devRate: 1,
    repGain: 0.9,
    fanGain: 0.9,
    incidentMult: 1,
    pressure: 0.5,
    offerMult: 1.6,
    ageShift: 0,
    duel: 0.5,
    teamDrift: -3,
  },
  {
    id: 'grafter',
    label: 'Grafter',
    emoji: '🛠️',
    description: 'First in the factory, last out of the simulator. You improve faster than anyone.',
    devRate: 1.35,
    repGain: 1,
    fanGain: 0.9,
    incidentMult: 0.9,
    pressure: 0.6,
    offerMult: 1,
    ageShift: 1,
    duel: 0,
    teamDrift: 3,
  },
  {
    id: 'showman',
    label: 'Showman',
    emoji: '🎤',
    description: 'Donuts, flags, viral clips. Fans adore you, sponsors pay for it.',
    devRate: 0.95,
    repGain: 1.1,
    fanGain: 2,
    incidentMult: 1.1,
    pressure: 0.6,
    offerMult: 1.1,
    ageShift: 0,
    duel: 0.5,
    teamDrift: 0,
  },
  {
    id: 'hothead',
    label: 'Hothead',
    emoji: '🌋',
    description: 'Fast, furious and permanently on the stewards’ radar.',
    devRate: 1,
    repGain: 0.9,
    fanGain: 1.3,
    incidentMult: 1.45,
    pressure: 0.3,
    offerMult: 0.9,
    ageShift: -1,
    duel: 1.5,
    teamDrift: -2,
  },
  {
    id: 'lateBloomer',
    label: 'Late Bloomer',
    emoji: '🌱',
    description: 'Written off at 20, dangerous at 30. You peak later and last longer.',
    devRate: 0.9,
    repGain: 1,
    fanGain: 1,
    incidentMult: 1,
    pressure: 0.6,
    offerMult: 0.9,
    ageShift: 3,
    duel: 0,
    teamDrift: 1,
  },
  {
    id: 'partyAnimal',
    label: 'Party Animal',
    emoji: '🪩',
    description: 'Monaco yacht parties, Vegas afterparties. Talented, when you turn up.',
    devRate: 0.85,
    repGain: 0.9,
    fanGain: 1.6,
    incidentMult: 1.15,
    pressure: 0.4,
    offerMult: 1,
    ageShift: -2,
    duel: 0.5,
    teamDrift: -1,
  },
];

export const PERSONALITY_MAP = Object.fromEntries(PERSONALITIES.map((p) => [p.id, p])) as Record<string, PersonalityDef>;

export function personality(id: string): PersonalityDef {
  return PERSONALITY_MAP[id] ?? PERSONALITIES[0];
}

export const FAMILIES: FamilyDef[] = [
  {
    id: 'dynasty',
    label: 'Racing Dynasty',
    emoji: '🏎️',
    description: 'A famous surname opens every paddock door — and invites endless comparisons.',
    budget: 900,
    reputation: 12,
    money: 2500,
    morale: 0,
  },
  {
    id: 'wealthy',
    label: 'Rich Family',
    emoji: '💰',
    description: 'Money talks. You can buy seats — and critics will never let you forget it.',
    budget: 1800,
    reputation: 2,
    money: 6000,
    morale: 0,
  },
  {
    id: 'comfortable',
    label: 'Comfortable',
    emoji: '🏡',
    description: 'Enough to get started, not enough to buy your way up.',
    budget: 350,
    reputation: 0,
    money: 400,
    morale: 2,
  },
  {
    id: 'working',
    label: 'Working Class',
    emoji: '🔧',
    description: 'Every set of tyres was a sacrifice. You race like it.',
    budget: 60,
    reputation: 0,
    money: 40,
    morale: 6,
  },
  {
    id: 'poor',
    label: 'Poor Family',
    emoji: '🥫',
    description: 'Borrowed karts and crowdfunding. Nobody hungrier on the grid.',
    budget: 0,
    reputation: 0,
    money: 5,
    morale: 10,
  },
];

export const FAMILY_MAP = Object.fromEntries(FAMILIES.map((f) => [f.id, f])) as Record<string, FamilyDef>;

export function family(id: string | undefined): FamilyDef {
  return (id && FAMILY_MAP[id]) || FAMILIES[2];
}
